apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ttriage.fullname" . }}-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "ttriage.fullname" . }}-backend
  template:
    metadata:
      labels:
        app: {{ include "ttriage.fullname" . }}-backend
    spec:
      initContainers:
        - name: init-wait
          image: busybox:1.28
          command: ['sh', '-c', 'sleep 10']
      containers:
        - name: {{ .Chart.Name }}-backend
          securityContext:
            {{- toYaml .Values.backend.securityContext | nindent 12 }}
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag | default .Chart.AppVersion }}"
          env:
            - name: app.url
              value: localhost
            - name: db.dialect
              value: org.hibernate.dialect.PostgreSQL95Dialect
            - name: db.drive
              value: org.postgresql.Driver
           {{- if .Values.postgresql.enabled }}
            - name: db.username
              value: {{ .Values.postgresql.global.postgresql.postgresqlUsername | quote }}
            - name: db.password
              value: {{ .Values.postgresql.global.postgresql.postgresqlPassword }}
              #valueFrom:
                #secretKeyRef:
                  #name: {{ .Release.Name }}-postgresql
                  #key: postgresql-password
           {{- else }}
            - name: db.username
              value: {{ .Values.externalDatabase.user | quote }}
            - name: db.password
              valueFrom:
                secretKeyRef:
                  name: {{ printf "%s-%s" .Release.Name "externaldb" }}
                  key: db-password
           {{- end }}
              value: ttriage
            - name: db.platform
              value: postgres
            - name: db.populate
              value: "false"
            - name: db.profile
              value: prod
           {{- if .Values.postgresql.enabled }}
            - name: db.url
              value: jdbc:postgresql://{{ .Release.Name }}-postgresql:5432/ttriage
           {{- else }}
            - name: db.url
              value: jdbc:postgresql://{{ .Values.externalDatabase.host }}:{{ .Values.externalDatabase.port }}/{{ .Values.externalDatabase.dbName }}
           {{- end }}
            - name: google.client-id
              value: {{ .Values.backend.ttriageEnv.googleClientId | quote | quote  }}
            - name: google.client-secret
              value: {{ .Values.backend.ttriageEnv.googleClientSecret  | quote | quote }}
            - name: h2.console
              value: {{ .Values.backend.ttriageEnv.h2 | quote }}
          args:
           - java
           - -Xmx256M
           - -Xms128M
           - -Dserver.port=80
           - -Dspring.profiles.active=prod
           - -jar
           - /app/app.jar
          ports:
            - name: http
              containerPort: 80
