apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-%s" .Release.Name "ttriagedb"  }}
type: Opaque
data:
  db-password: {{ .Values.postgresql.global.postgresql.postgresqlPassword | b64enc | quote }}
