apiVersion: v1
kind: Service
metadata:
  name: {{ include "ttriage.fullname" . }}-backend
spec:
  type: {{ .Values.backend.service.type }}
  {{- if and .Values.backend.service.loadBalancerIP (eq .Values.backend.service.type "LoadBalancer")}}
  loadBalancer: {{ .Values.backend.service.loadBalancerIP }}
  {{- end}}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: http
      name: http
     {{ if eq .Values.backend.service.type "NodePort" }}
      nodePort: {{ .Values.backend.service.nodePort }}
      {{- end }}
  selector:
    {{- include "ttriage.selectorLabels" . | nindent 4 }}
