apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "ttriage.fullname" . }}
data:
  config: |
    version: {{ .Values.frontend.config.version }}
    port: {{ .Values.frontend.config.port }}
    apiurl: {{ .Values.frontend.config.backEndHost }}:{{ .Values.frontend.config.backEndHostPort }}
    login:
      google: {{ .Values.frontend.config.login.google }}
      onelogin: {{ .Values.frontend.config.login.onelogin }}
      internal: {{ .Values.frontend.config.login.internal }}
    
