apiVersion: v1
kind: Service
metadata:
  name: {{ include "ttriage.fullname" . }}-front
spec:
  type: {{ .Values.frontend.service.type }}
  {{- if and .Values.frontend.service.loadBalancerIP (eq .Values.frontend.service.type "LoadBalancer")}}
  loadBalancer: {{ .Values.frontend.service.loadBalancerIP }}
  {{- end}}
  
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "ttriage.selectorLabels" . | nindent 4 }}
